# -*- coding: utf-8 -*-
"""HW_5_CS_Sina_Q_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u2TEXsb33a2iQ36AEBtEyHIos2kmYrzO
"""

from google.colab import drive
drive.mount ('/content/drive')

# Assuming your files are located in the following paths:
models_path = '/content/drive/MyDrive/HW_5_CS/models.py'

# Import the files
import sys
sys.path.append('/content/drive/MyDrive/HW_5_CS')

# Now you can import your models and utils as if they were in the Colab environment
import  models

import os
import shutil
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

from models import *

save_figures = True
save_dir = './Report/figs'
questions_number = '2_1'
if save_figures:
    if not os.path.exists(save_dir):
        os.makedirs(save_dir, exist_ok=True)

"""Part_1"""

ml_model = MorrisLecarModel()
hh_model = HodgkinHuxleyModel()

t_start = 0
t_end = 300
dt = 0.01
t = np.arange(t_start, t_end, dt)

input_current = lambda t: 95 if t>=20 else 0.0

sol_ml = solve_ivp(
    lambda t, Y: ml_model(Y, I=input_current(t)),
    t_span=[t_start, t_end],
    y0=ml_model.get_initial_state(),
    t_eval=t,
    vectorized=True,
    method = 'RK23',
)

V, w = sol_ml.y
I_Ca, I_K, I_L = ml_model.get_currents(*sol_ml.y)

k = 0

fig, ax = plt.subplots(nrows=2, ncols=2, sharex=True, figsize=(12.8, 4.8))
ax[0,0].plot(sol_ml.t, np.vectorize(input_current)(sol_ml.t))
ax[0,0].set_xlabel('$t\;[m\mathrm{s}]$')
ax[0,0].set_ylabel('$I\;[\mu\mathrm{A}/c\mathrm{m}^2]$')
ax[0,0].set_title('Input Current')
ax[0,0].grid()
ax[0,1].plot(sol_ml.t, V)
ax[0,1].set_ylim([-90,70])
ax[0,1].set_xlabel('$t\;[m\mathrm{s}]$')
ax[0,1].set_ylabel('$V\;[m\mathrm{V}]$')
ax[0,1].set_title('Membrane Voltage')
ax[0,1].grid()
ax[1,0].plot(sol_ml.t, I_Ca, label='$I_\mathrm{Ca}$')
ax[1,0].plot(sol_ml.t, I_K, label='$I_\mathrm{K}$')
ax[1,0].plot(sol_ml.t, I_L, label='$I_\mathrm{L}$')
ax[1,0].set_xlabel('$t\;[m\mathrm{s}]$')
ax[1,0].set_ylabel('$I\;[\mu\mathrm{A}/c\mathrm{m}^2]$')
ax[1,0].set_title('Ion and leak currents')
ax[1,0].legend(loc='lower right')
ax[1,0].grid()
ax[1,1].plot(sol_ml.t, w, label='$w$')
ax[1,1].set_ylim([-0.1,1.1])
ax[1,1].set_xlabel('$t\;[m\mathrm{s}]$')
ax[1,1].set_title('Gating Variables')
ax[1,1].legend(loc='lower right')
ax[1,1].grid()
fig.suptitle('Moris-Lecar Model Step Response')
plt.tight_layout()
if save_figures:
    plt.savefig(f'{save_dir}/{questions_number}_1_{k}.png')
    k += 1

plt.figure()
plt.plot(V, w)
plt.xlabel('$V\;[m\mathrm{V}]$')
plt.ylabel('$w$ (Potassium gating variable)')
plt.title('Phase portrait of the Moris-Lecar model ($w$-$V$)')
plt.grid()
if save_figures:
    plt.savefig(f'{save_dir}/{questions_number}_1_{k}.png')
    k += 1

input_current = lambda t: 8 if t>=20 else 0.0

sol_hh = solve_ivp(
    lambda t, Y: hh_model(Y, I=input_current(t)),
    t_span=[t_start, t_end],
    y0=hh_model.get_initial_state(),
    t_eval=t,
    vectorized=True,
    method = 'RK23',
)

V, n, m, h = sol_hh.y
I_Na, I_K, I_L = hh_model.get_currents(*sol_hh.y)

fig, ax = plt.subplots(nrows=2, ncols=2, sharex=True, figsize=(12.8, 4.8))
ax[0,0].plot(sol_hh.t, np.vectorize(input_current)(sol_hh.t))
ax[0,0].set_xlabel('$t\;[m\mathrm{s}]$')
ax[0,0].set_ylabel('$I\;[\mu\mathrm{A}/c\mathrm{m}^2]$')
ax[0,0].set_title('Input Current')
ax[0,0].grid()
ax[0,1].plot(sol_hh.t, V)
ax[0,1].set_ylim([-90,70])
ax[0,1].set_xlabel('$t\;[m\mathrm{s}]$')
ax[0,1].set_ylabel('$V\;[m\mathrm{V}]$')
ax[0,1].set_title('Membrane Voltage')
ax[0,1].grid()
ax[1,0].plot(sol_hh.t, I_Na, label='$I_\mathrm{Ca}$')
ax[1,0].plot(sol_hh.t, I_K, label='$I_\mathrm{K}$')
ax[1,0].plot(sol_hh.t, I_L, label='$I_\mathrm{L}$')
ax[1,0].set_xlabel('$t\;[m\mathrm{s}]$')
ax[1,0].set_ylabel('$I\;[\mu\mathrm{A}/c\mathrm{m}^2]$')
ax[1,0].set_title('Ion and leak currents')
ax[1,0].legend(loc='lower right')
ax[1,0].grid()
ax[1,1].plot(sol_hh.t, n, label='$n$')
ax[1,1].plot(sol_hh.t, m, label='$m$')
ax[1,1].plot(sol_hh.t, h, label='$h$')
ax[1,1].set_ylim([-0.1,1.1])
ax[1,1].set_xlabel('$t\;[m\mathrm{s}]$')
ax[1,1].set_title('Gating Variables')
ax[1,1].legend(loc='lower right')
ax[1,1].grid()
fig.suptitle('Hodgkin-Huxley Model Step Response')
plt.tight_layout()
if save_figures:
    plt.savefig(f'{save_dir}/{questions_number}_1_{k}.png')
    k += 1

plt.figure()
plt.plot(V, n, label='$n$ (Pottasium gating variable)')
plt.plot(V, m, label='$m$ (Sodium gating variable)')
plt.plot(V, h, label='$h$ (Sodium gating variable)')
plt.xlabel('$V\;[m\mathrm{V}]$')
plt.ylabel('Gating Variables')
plt.title('Phase portrait of the Hodgkin-Huxley model')
plt.legend()
plt.grid()
if save_figures:
    plt.savefig(f'{save_dir}/{questions_number}_1_{k}.png')
    k += 1

"""Part_2"""

V_hh, n_hh, _, _ = sol_hh.y
V_ml, w_ml = sol_ml.y

k = 0

plt.figure()
plt.plot(V_hh, n_hh, label='$n$ (Potassium gating variable HH model)', color='C1')
plt.plot(V_ml, w_ml, label='$w$ (Potassium gating variable ML model)', color='C0')
plt.xlabel('$V\;[m\mathrm{V}]$')
plt.ylabel('Gating Variables')
plt.title('Phase portrait of the HH and ML model')
plt.legend()
plt.grid()
if save_figures:
    plt.savefig(f'{save_dir}/{questions_number}_2_{k}.png')
    k += 1

plt.show()